# Rafael Dutra
image: docker:latest

services:
  - docker:dind
  - raffaeldutra/docker-gohugo

before_script:
  - docker info

stages:
  - deploy

pages:
  stage: deploy
  script:
    - docker run -it -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/docker-gohugo
  artifacts:
    paths:
    - public
  only:
    - develop
