# Rafael Dutra
image: docker:latest

services:
  - docker:dind

variables:
  AWS_DEFAULT_REGION: sa-east-1
  BUCKET_NAME_STATIC_RESUME: rafaeldutra.me/resume

before_script:
  - mkdir -p public/resume
  - apk update && apk add curl

stages:
  - build
  - deploy
  - testing

build-hugo:
  stage: build
  script:
    - docker run --rm -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/docker-gohugo
  artifacts:
    paths:
    - public
  only:
    - develop

pages:
  stage: deploy
  script:
    - docker run --rm -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/docker-gohugo
    - curl
      --form input_files[]=@content/page/cv/resume.md
      --form from=markdown
      --form to=pdf
      --form other_files[]=@content/page/cv/css/resume.css
      http://c.docverter.com/convert > public/resume/rafael-dutra-full-resume.pdf
    - curl
      --form input_files[]=@content/page/cv/resume.pt-br.md
      --form from=markdown
      --form to=pdf
      --form other_files[]=@content/page/cv/css/resume.css
      http://c.docverter.com/convert > public/resume/rafael-dutra-full-resume-pt-br.pdf
  artifacts:
    paths:
    - public
  only:
    - develop

testing:
  stage: testing
  script:
    - docker run --rm byrnedo/alpine-curl curl --silent rafaeldutra.me > /dev/null || exit 1

deploy-resume-s3:
  image: python:latest
  stage: deploy
  tags:
    - gitlab-org
  before_script:
    - pip install awscli
  script:
    - aws s3 cp public/rafael-dutra-full-resume.pdf s3://${BUCKET_NAME_STATIC_RESUME}/
    - aws s3 cp public/rafael-dutra-full-resume-pt-br.pdf s3://${BUCKET_NAME_STATIC_RESUME}/
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME_STATIC_RESUME}.s3-${AWS_DEFAULT_REGION}.amazonaws.com
  only:
    - develop
