# Rafael Dutra
image: raffaeldutra/docker-gohugo

stages:
  - deploy

pages:
  stage: deploy
  script:
    - docker run -it -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/docker-gohugo
  artifacts:
    paths:
    - public
  only:
    - develop
