# Rafael Dutra
image: raffaeldutra/docker-gohugo

before_script:
  - mkdir -p public/resume

github_pages:
  script:
  - docker run -it -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/docker-gohugo
  - curl
    --form input_files[]=@content/page/cv/resume.md
    --form from=markdown
    --form to=pdf
    --form other_files[]=@content/page/cv/css/resume.css
    http://c.docverter.com/convert > public/resume/rafael-dutra-full-resume.pdf
  - curl
    --form input_files[]=@content/page/cv/resume.pt-br.md
    --form from=markdown
    --form to=pdf
    --form other_files[]=@content/page/cv/css/resume.css
    http://c.docverter.com/convert > public/resume/rafael-dutra-full-resume-pt-br.pdf
  artifacts:
    paths:
    - public
  only:
  - master
