# Rafael Dutra
sudo: required

services:
  - docker

branches:
  only:
  - develop

before_install:
  - mkdir -p public/resume

before_script:
    cat config.toml | grep baseurl 2>/dev/null >/dev/null || exit 1

script:
  - docker run --rm -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/docker-gohugo
  - curl
    --form input_files[]=@content/cv/me.en.md
    --form from=markdown
    --form to=pdf
    --form other_files[]=@content/cv/css/resume.css
    http://c.docverter.com/convert > public/resume/rafael-dutra-resume-en.pdf
  - curl
    --form input_files[]=@content/cv/me.md
    --form from=markdown
    --form to=pdf
    --form other_files[]=@content/cv/css/resume.css
    http://c.docverter.com/convert > public/resume/rafael-dutra-resume.pdf
  - docker run --rm byrnedo/alpine-curl curl --silent rafaeldutra.me > /dev/null || exit 1
deploy:
  name: "rafaeldutra.me deployment"
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  target_branch: master
  on:
    branch: develop
  fqdn: rafaeldutra.me
