# Rafael Dutra
sudo: required

services:
  - docker

branches:
  only:
  - develop

before_install:
  - mkdir -p public/resume

script:
  - docker run -it -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/docker-gohugo
  - curl
    --form input_files[]=@content/page/cv/resume.md
    --form from=markdown
    --form to=pdf
    --form other_files[]=@content/page/cv/css/resume.css
    http://c.docverter.com/convert > public/resume/rafael-dutra-resume.pdf
  - curl
    --form input_files[]=@content/page/cv/resume.pt-br.md
    --form from=markdown
    --form to=pdf
    --form other_files[]=@content/page/cv/css/resume.css
    http://c.docverter.com/convert > public/resume/rafael-dutra-resume.pt-br.pdf

deploy:
  name: "rafaeldutra.me deployment"
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  target_branch: master
  on:
    branch: develop
  fqdn: rafaeldutra.me
