# Rafael Dutra
sudo: required

services:
  - docker

script:
  - docker build --no-cache -t raffaeldutra/gohugo .
  - docker run -it -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/gohugo

deploy:
  name: "rafaeldutra.me deployment"
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  target_branch: master
  on:
    branch: develop
  fqdn: rafaeldutra.me
