baseurl = "https://rafaeldutra.me"
defaultContentLanguage = "en"
languageCode = "en-us"
theme = "beautifulhugo"
pygmentsUseClassic = false
pygmentCodeFences = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentOptions = "linenos=table"
googleAnalytics = "UA-92899338-1"
publishDir = "public"
layoutDir = "/src/layouts"
defaultExtension = "html"
metaDataFormat = "yaml"
#disqusShortname = "raffaeldutra-github-io"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[Params]
  subtitle = "knowledgement and ideas"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false
  rss = true
  comments = false
  readingTime = true
  useHLJS = true
  socialShare = false

[permalinks]
post = "/:year/:month/:day/:slug"
blog = "/blog/:year/:month/:day/:slug"

[Author]
  name = "Rafael Dutra"
  website = "rafaeldutra.me"
  email = "raffaeldutra@gmail.com"
  googleplus = "+RafaelDutra"
  github = "raffaeldutra"
  gitlab = "raffaeldutra"
  twitter = "raffaeldutra"
  linkedin = "rafaeldutra"
  youtube = "watch?v=jXqfY0Nn53Q&list=PLZJThJjvPpHlgV4AjZDstipTZhEuV_OIz"
  telegram = "raffaeldutra"

[Languages]
[Languages.en]
  title = "#/share"
  languageName = "English"

[[Languages.en.menu.main]]
  name = "HOME"
  url = "/blog"
  weight = 2

[[Languages.en.menu.main]]
  identifier = "cv"
  name = "CURRICULUM"
  weight = 3

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Downloads"
  url = "/page/cv/downloads"
  weight = 30

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Resume"
  url = "/page/cv/resume"
  weight = 31

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Mini"
  url = "/page/cv/mini"
  weight = 32

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Experience"
  url = "/page/cv/experience"
  weight = 32

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Talks"
  url = "/page/presentations/talks"
  weight = 33

[[Languages.en.menu.main]]
  name = "ABOUT"
  url = "/page/about/me"
  weight = 5

[[Languages.en.menu.main]]
  name = "Docker"
  url = "https://docker.rafaeldutra.me"
  weight = 5

[Languages.pt-br]
  title = "#/share beer"
  languageName = "Português"
  url = "/pt-br/blog"

[[Languages.pt-br.menu.main]]
  url    = "/pt-br/blog"
  name   = "HOME"
  weight = 2

[[Languages.pt-br.menu.main]]
  identifier = "cv"
  name = "Curriculo"
  weight = 3

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Downloads"
  url = "/pt-br/page/cv/Downloads"
  weight = 30

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Resume"
  url = "/pt-br/page/cv/resume"
  weight = 31

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Mini"
  url = "/pt-br/page/cv/mini"
  weight = 32

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Experience"
  url = "/page/cv/Experience"
  weight = 32

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Palestras"
  url = "/pt-br/page/presentations/talks"
  weight = 33

[[Languages.pt-br.menu.main]]
  name = "Sobre"
  url = "/pt-br/page/about/me"
  weight = 5

[[Languages.pt-br.menu.main]]
  name = "Docker"
  url = "https://docker.rafaeldutra.me"
  weight = 5
