baseurl = "https://raffaeldutra.github.io"
defaultContentLanguage = "en"
languageCode = "en-us"
theme = "beautifulhugo"
pygmentsuseclasses = true
pygmentCodeFences = true
googleAnalytics = "UA-92899338-1"
#disqusShortname = "raffaeldutra-github-io"

[Params]
subtitle = "knowledgement and ideas"
logo = "img/avatar-icon.png"
favicon = "img/favicon.ico"
commit = false

[Params.cv]
age = 30

[Author]
name = "Rafael Dutra"
email = "raffaeldutra@gmail.com"
facebook = "sysrafaeldutra"
googleplus = "+RafaelDutra"
github = "raffaeldutra"
twitter = "rafaeldutra"
linkedin = "raffaeldutra"
instagram = "raff4eldutra"

[Languages]
[Languages.en]
title = "#/share beer"
languageName = "English"

[[Languages.en.menu.main]]
name = "PTBR"
url = "/ptbr"
weight = 1

[[Languages.en.menu.main]]
name = "MAIN"
url = "/"
weight = 2

[[Languages.en.menu.main]]
name = "CV"
url = "/page/cv"
weight = 3

[[Languages.en.menu.main]]
name = "PRESENTATIONS"
url = "/page/presentations"
weight = 4

[[Languages.en.menu.main]]
name = "ABOUT"
url = "/page/about/me"
weight = 5


[Languages.ptbr]
title = "#/share beer"
languageName = "Português"

[[Languages.ptbr.menu.main]]
url    = "/"
name   = "EN"
weight = 1

[[Languages.ptbr.menu.main]]
url    = "/ptbr"
name   = "PRINCIPAL"
weight = 2

[[Languages.ptbr.menu.main]]
name = "CV"
url = "/ptbr/page/cv"
weight = 3

[[Languages.ptbr.menu.main]]
name = "PALESTRAS"
url = "/ptbr/page/presentations"
weight = 4

[[Languages.ptbr.menu.main]]
name = "SOBRE MIM"
url = "/ptbr/page/about/me"
weight = 5
