baseurl = "https://rafaeldutra.me"
defaultContentLanguage = "pt-br"
languageCode = "pt-br"
theme = "beautifulhugo"
pygmentsUseClassic = false
pygmentCodeFences = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentOptions = "linenos=table"
publishDir = "public"
layoutDir = "/src/layouts"
defaultExtension = "html"
metaDataFormat = "yaml"
#disqusShortname = "raffaeldutra-github-io"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[Params]
  subtitle = "knowledgement and ideas"
  logo = "img/avatar-icon.png"
  favicon = "images/favicon.ico"
  commit = false
  rss = true
  comments = false
  readingTime = true
  useHLJS = true
  socialShare = false

[permalinks]
post = "/:year/:month/:day/:slug"
blog = "/blog/:year/:month/:day/:slug"

[Author]
  name = "Rafael Dutra"
  website = "rafaeldutra.me"
  email = "raffaeldutra@gmail.com"
  github = "raffaeldutra"
  gitlab = "raffaeldutra"
  twitter = "raffaeldutra"
  linkedin = "rafaeldutra"
  youtube = "watch?v=jXqfY0Nn53Q&list=PLZJThJjvPpHlgV4AjZDstipTZhEuV_OIz"
  telegram = "raffaeldutra"

[Languages]
[Languages.en]
  title = "#/share"
  languageName = "English"

[[Languages.en.menu.main]]
  identifier = "cv"
  name = "CURRICULUM"
  weight = 3

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Downloads"
  url = "/en/cv/downloads"
  weight = 30

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Resume"
  url = "/en/cv/me"
  weight = 31

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Mini"
  url = "/en/cv/mini"
  weight = 32

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Experience"
  url = "/en/cv/experience"
  weight = 32

[[Languages.en.menu.main]]
  parent = "cv"
  name = "Talks"
  url = "/en/presentations/talks"
  weight = 33

[[Languages.en.menu.main]]
  name = "ABOUT"
  url = "/en/about/me"
  weight = 5

[[Languages.en.menu.main]]
  name = "Docker"
  url = "https://docker.rafaeldutra.me"
  weight = 5

[Languages.pt-br]
  title = "#/share"
  languageName = "Português"
  url = "cv/me"

[[Languages.pt-br.menu.main]]
  identifier = "cv"
  name = "Curriculo"
  weight = 3

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Downloads"
  url = "cv/downloads"
  weight = 30

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Currículo"
  url = "cv/me"
  weight = 31

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Mini"
  url = "cv/mini"
  weight = 32

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Experiência"
  url = "/cv/Experience"
  weight = 32

[[Languages.pt-br.menu.main]]
  parent = "cv"
  name = "Palestras"
  url = "presentations/talks"
  weight = 33

[[Languages.pt-br.menu.main]]
  name = "Sobre"
  url = "about/me"
  weight = 5

[[Languages.pt-br.menu.main]]
  name = "Docker"
  url = "https://docker.rafaeldutra.me"
  weight = 5
