baseurl = "https://raffaeldutra.github.io"
defaultContentLanguage = "en"
languageCode = "en-us"
theme = "beautifulhugo"
pygmentsUseClassic = false
pygmentCodeFences = true
googleAnalytics = "UA-92899338-1"
publishDir = "public"
layoutDir = "/src/layouts"
defaultExtension = "html"
#disqusShortname = "raffaeldutra-github-io"

[Params]
subtitle = "knowledgement and ideas"
logo = "img/avatar-icon.png"
favicon = "img/favicon.ico"
commit = false

[permalinks]
post = "/:year/:month/:day/:slug"
blog = "/blog/:year/:month/:day/:slug"

[Author]
name = "Rafael Dutra"
email = "raffaeldutra@gmail.com"
googleplus = "+RafaelDutra"
github = "raffaeldutra"
twitter = "raffaeldutra"
linkedin = "rafaeldutra"
instagram = "raff4eldutra"

[Languages]
[Languages.en]
title = "#/share beer"
languageName = "English"

[[Languages.en.menu.main]]
name = "HOME"
url = "/blog"
weight = 2

[[Languages.en.menu.main]]
identifier = "cv"
name = "CURRICULUM"
weight = 3

[[Languages.en.menu.main]]
parent = "cv"
name = "Index/Downloads"
url = "/page/cv"
weight = 30

[[Languages.en.menu.main]]
parent = "cv"
name = "Resume"
url = "/page/cv/resume"
weight = 31

[[Languages.en.menu.main]]
parent = "cv"
name = "Mini"
url = "/page/cv/mini"
weight = 32

[[Languages.en.menu.main]]
parent = "cv"
name = "Talks"
url = "/page/presentations"
weight = 33

[[Languages.en.menu.main]]
name = "ABOUT"
url = "/page/about/me"
weight = 5


[Languages.ptbr]
title = "#/share beer"
languageName = "Português"
url = "/ptbr/blog"

[[Languages.ptbr.menu.main]]
url    = "/ptbr/blog"
name   = "HOME"
weight = 2

[[Languages.ptbr.menu.main]]
identifier = "cv"
name = "Curriculo"
weight = 3

[[Languages.ptbr.menu.main]]
parent = "cv"
name = "Index/Downloads"
url = "/ptbr/page/cv"
weight = 30

[[Languages.ptbr.menu.main]]
parent = "cv"
name = "Resume"
url = "/ptbr/page/cv/resume"
weight = 31

[[Languages.ptbr.menu.main]]
parent = "cv"
name = "Mini"
url = "/ptbr/page/cv/mini"
weight = 32

[[Languages.ptbr.menu.main]]
parent = "cv"
name = "Palestras"
url = "/ptbr/page/presentations"
weight = 33

[[Languages.ptbr.menu.main]]
name = "SOBRE MIM"
url = "/ptbr/page/about/me"
weight = 5
