image: docker:latest

variables:
  - HOST: registry.gitlab.com
  - NAMESPACE: raffaeldutra
  - PROJECT: raffaeldutra.github.io

services:
  - docker:dind

stages:
  - image

.registry: &registry
  script:
    - |
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      docker build -t $CI_REGISTRY/${NAMESPACE}/${PROJECT}/${PROJECT}:latest .
      docker push ${CI_REGISTRY}/${NAMESPACE}/${PROJECT}/${PROJECT}:latest

image-creation:
  stage: image
  <<: *registry
