image: docker:latest

services:
  - docker:dind

before_script:
  - mkdir -p public/resume
  - apk update && apk add curl

stages:
  - publishing
  - deploy-s3
  - deploy-page
  - testing

.publishing: &publishing
  image: docker:latest
  stage: publishing
  script:
    - |
      docker run --rm -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/docker-gohugo

      curl \
      --form input_files[]=@content/cv/me.en.md \
      --form from=markdown \
      --form to=pdf \
      --form other_files[]=@content/cv/css/resume.css  \
      http://c.docverter.com/convert > public/resume/rafael-dutra-resume-en.pdf

      curl \
      --form input_files[]=@content/cv/me.md \
      --form from=markdown \
      --form to=pdf \
      --form other_files[]=@content/cv/css/resume.css \
      http://c.docverter.com/convert > public/resume/rafael-dutra-resume.pdf
  artifacts:
    paths:
      - public

publishing:
  stage: publishing
  <<: *publishing

.deploy-s3: &deploy-s3
  image: python:latest
  stage: deploy-s3
  before_script:
    - pip install awscli
  script:
    - aws s3 cp public s3://${BUCKET_NAME_STATIC} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
  artifacts:
    paths:
      - public

deploy-s3-branches:
  variables:
    BUCKET_NAME_STATIC: ${CI_COMMIT_REF_SLUG}.rafaeldutra.me
  <<: *deploy-s3
  only:
    - branches
  except:
    - develop

deploy-s3-prod:
  <<: *deploy-s3
  variables:
    BUCKET_NAME_STATIC: www.rafaeldutra.me
  only:
    - develop
  when: manual

pages:
  stage: deploy-page
  <<: *publishing
  only:
    - develop
  when: manual
  artifacts:
    paths:
      - public

.testing: &testing
  stage: testing
  script:
    - docker run --rm byrnedo/alpine-curl curl --silent ${BUCKET_NAME_STATIC} > /dev/null || exit 1

testing-branches:
  variables:
    BUCKET_NAME_STATIC: ${CI_COMMIT_REF_SLUG}.rafaeldutra.me
  <<: *testing
  only:
    - branches
  except:
    - develop

testng-prod:
  variables:
    BUCKET_NAME_STATIC: www.rafaeldutra.me
  <<: *testing
  only:
    - develop