image: docker:latest

variables:
  variables:
    IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

services:
  - docker:dind

stages:
  - image

.registry: &registry
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${IMAGE_TAG} .
    - docker push ${IMAGE_TAG}

dev-image-creation:
  stage: image
  <<: *registry
  only:
    - develop
