image: docker:latest

variables:
  - HOST: registry.gitlab.com
  - NAMESPACE: raffaeldutra
  - IMAGE: raffaeldutra.github.io

services:
  - docker:dind

stages:
  - image

.registry: &registry
  script:
    - |
      docker login ${HOST} -u ${GITLAB_USERNAME} -p ${GITLAB_TOKEN}
      docker build -t ${HOST}/${NAMESPACE}/${IMAGE}:${CI_COMMIT_REF_NAME} .
      docker push ${HOST}/${NAMESPACE}/${IMAGE}

image:
  stage: image
  <<: *registry
