image: docker:latest

variables:
  - HOST: registry.gitlab.com/
  - NAMESPACE: raffaeldutra
  - IMAGE: raffaeldutra.github.io

services:
  - docker:dind

stages:
  - image-creation

.image-creation: &image-creation
  image: docker:latest
  stage: image-creation
  script:
    - |
      docker login ${HOST} -u ${GITLAB_USERNAME} -p ${GITLAB_TOKEN}
      docker build -t ${HOST}/${NAMESPACE}/${IMAGE} .
      docker push ${HOST}/${NAMESPACE}/${IMAGE}
  only:
    - master
