name: Build and Deploy
on:
  push:
    branches:
      - develop
      - deployment
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Start Docker registry
        run: |
          docker run -d -p 5000:5000 -v ${REGISTRY_PATH}:/var/lib/registry --name registry registry:2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Testing Configuration
        run: |
          cat config.toml | grep baseurl 2>/dev/null >/dev/null || exit 1

      - name: Install and Build
        run: |
          mkdir -p public/resume
          docker run --rm -v $(pwd):/src -v $(pwd)/public:/src/public raffaeldutra/docker-gohugo:v1.1
          curl \
          --form input_files[]=@content/cv/me.en.md \
          --form from=markdown \
          --form to=pdf \
          --form other_files[]=@content/cv/css/resume.css \
          http://c.docverter.com/convert > public/resume/rafael-dutra-resume-en.pdf
          curl \
          --form input_files[]=@content/cv/me.md \
          --form from=markdown \
          --form to=pdf \
          --form other_files[]=@content/cv/css/resume.css \
          http://c.docverter.com/convert > public/resume/rafael-dutra-resume.pdf

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./public
          file: ./Dockerfile.prd
          push: true
          platforms: linux/amd64
          tags: raffaeldutra/rafaeldutra-me:latest
